setup:
- installHelmChart:
    namespace: gloo-system
    releaseName: gloo
    releaseUri: https://storage.googleapis.com/gloo-ee-helm/charts/gloo-ee-1.3.0.tgz
    set:
      license_key: env:LICENSE_KEY
    valuesFiles:
    - values.yaml
    waitForPods: true
- bash:
    inline: kubectl delete virtualservices.gateway.solo.io -n gloo-system --all
- bash:
    inline: glooctl check
- patch:
    kubeType: settings
    name: default
    namespace: gloo-system
    patchType: merge
    path: settings-patch-revert.yaml
- bash:
    inline: kubectl delete ns echo foxtrot --ignore-not-found
steps:
- id: patch-settings
  patch:
    kubeType: settings
    name: default
    namespace: gloo-system
    patchType: merge
    path: settings-patch.yaml
- apply:
    path: vs.yaml
  id: deploy-vs
- apply:
    path: echo.yaml
  id: deploy-echo
- apply:
    path: foxtrot.yaml
  id: deploy-foxtrot
- id: wait-echo
  waitForPods:
    namespace: echo
- id: wait-foxtrot
  waitForPods:
    namespace: foxtrot
- curl:
    path: /echo
    responseBody: version:echo-v1
    service:
      name: gateway-proxy
      namespace: gloo-system
    statusCode: 200
- curl:
    path: /foxtrot
    responseBody: version:foxtrot-v1
    service:
      name: gateway-proxy
      namespace: gloo-system
    statusCode: 200
- apply:
    path: echo-v2.yaml
  id: deploy-echo-v2
- apply:
    path: upstream-shadow.yaml
  id: deploy-shadow-upstream
- id: wait-echo
  waitForPods:
    namespace: echo
- apply:
    path: rt-shadow.yaml
  id: deploy-route-shadowing
- curl:
    path: /echo
    responseBody: version:echo-v1
    service:
      name: gateway-proxy
      namespace: gloo-system
    statusCode: 200
