steps:
  - apply:
      manifest:
        path: vs.yaml
  - curl:
      service:
        name: gateway-proxy
        namespace: gloo-system
      path: /
      statusCode: 200
      responseBody: "version:v2"