spec:
  ratelimit:
    descriptors:
      - key: type
        value: Messenger
        rateLimit:
          requestsPerUnit: 2
          unit: MINUTE
      - key: type
        value: Whatsapp
        rateLimit:
          requestsPerUnit: 1
          unit: MINUTE
        descriptors:
          - key: number
            rateLimit:
              requestsPerUnit: 30
              unit: MINUTE
            value: "411"
            weight: 1
      - key: type
        rateLimit:
          requestsPerUnit: 1
          unit: MINUTE