{{- define "gloo.exampleVolume" -}}
- hostPath:
    path: /var/run/sds
    type: ""
    name: sds-uds-path
    - name: istio-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
  {{- end }}

  {{- define "gloo.exampleVolumeMount" -}}
- mountPath: /var/run/sds
  name: sds-uds-path
  {{- end }}

gloo:
  gatewayProxies:
    gatewayProxy:
      configMap:
        data: null
      extraVolumeHelper: sds-uds-path
      extraProxyVolumeMountHelper: sds-uds-path

