# Pre-requisites:
# - `valet ensure -f ../../common/workflows/deploy-gloo-enterprise.yaml`

title: Deploying Gloo with basic authentication
description:
  - >
    In this workflow, we'll set up the petstore application. Then we'll turn on basic authentication on the route,
    requiring a username and password be provided for the request to pass through Envoy.
  - This workflow assumes you already have a Kubernetes cluster, and you've installed Gloo Enterprise to the gloo-system namespace.
steps:
  - workflow:
      path: 1-deploy-app.yaml
  - workflow:
      path: 2-add-basic-auth.yaml