# Pre-requisites:
# - `valet ensure -f ../../common/workflows/deploy-gloo-enterprise.yaml`

title: Extending a Monlithic Application with Gloo
description:
  - >
    In this workflow, we'll set up the petclinic application, which is a "monolithic" application that
    consists of a backend server and a database. Once this application is configured in Gloo, we'll look at how you
    may deploy a new microservice and connect it to your application. Then we'll
    replace a buggy part of the application with a new implementation in AWS lambda.
  - >
    This workflow assumes you already have a Kubernetes cluster, and you've installed Gloo Enterprise to the gloo-system namespace.
steps:
  - workflow:
      path: ../../common/workflows/deploy-petclinic.yaml
  - workflow:
      path: 2-update-vets.yaml
  - workflow:
      path: 3-fix-contact.yaml