# Pre-requisites:
# - `valet ensure -f ../../common/workflows/deploy-gloo-enterprise.yaml`

title: Oauth with Google
description:
  - In this workflow, we'll deploy the petclinic application with Gloo. Then we'll set up oauth with Google as an OIDC provider.
  - This workflow assumes you already have a Kubernetes cluster, and you've installed Gloo Enterprise to the gloo-system namespace.
steps:
  - workflow:
      path: ../../../../common/workflows/deploy-petclinic.yaml
  - workflow:
      path: 2-setup-oauth.yaml