apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: echo-canary
  namespace: gloo-system
spec:
  kube:
    selector:
      app: echo
      version: v2
    serviceName: echo
    serviceNamespace: echo
    servicePort: 8080