apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: echo
  namespace: gloo-system
spec:
  kube:
    selector:
      app: echo
      version: v1
    serviceName: echo
    serviceNamespace: default
    servicePort: 8080