apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: echo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          multi:
            destinations:
              - weight: 0
                destination:
                  upstream:
                    name: echo
                    namespace: gloo-system
              - weight: 10
                destination:
                  upstream:
                    name: echo-canary
                    namespace: gloo-system