spec:
  ratelimit:
    descriptors:
      - key: apikey
        rate_limit:
          requests_per_unit: 1
          unit: MINUTE
        descriptors:
          - key: plan-per-minute
            value: BASIC
            rateLimit:
              requestsPerUnit: 2
              unit: MINUTE
          - key: plan-per-minute
            value: PLUS
            rateLimit:
              requestsPerUnit: 5
              unit: MINUTE
          - key: plan-per-hour
            value: BASIC
            rateLimit:
              requestsPerUnit: 20
              unit: HOUR
          - key: plan-per-hour
            value: PLUS
            rateLimit:
              requestsPerUnit: 50
              unit: HOUR