{{- $releaseName := .Release.Name }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $canary := .Values.routing.canary }}
{{- $version := .Values.routing.version }}

apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: {{ $releaseName }}-routes
  namespace: {{ $releaseNamespace }}
  labels:
    apiGroup: {{ .Values.routing.apiGroup }}
spec:
  routes:
    {{- range $route := .Values.routing.routes }}
    {{- if $canary }}
    - matchers:
        - headers:
            {{- range $headerName, $headerValue := $canary.headers }}
            - name: {{ $headerName }}
              value: {{ $headerValue }}
            {{- end }}
          prefix: {{ tpl $route.prefix $ }}
      routeAction:
        single:
          upstream:
            name: {{ $releaseName }}
            namespace: {{ $releaseNamespace }}
          subset:
            values:
              version: {{ $canary.version }}
    {{- end }}
    - matchers:
        - prefix: {{ tpl $route.prefix $ }}
      routeAction:
        {{- if $canary }}
        multi:
          destinations:
            - destination:
                upstream:
                  name: {{ $releaseName }}
                  namespace: {{ $releaseNamespace }}
                subset:
                  values:
                    version: {{ $version }}
              weight: {{ sub 100 $canary.weight }}
            - destination:
                upstream:
                  name: {{ $releaseName }}
                  namespace: {{ $releaseNamespace }}
                subset:
                  values:
                    version: {{ $canary.version }}
              weight: {{ add 0 $canary.weight }}
        {{- else }}
        single:
          upstream:
            name: {{ $releaseName }}
            namespace: {{ $releaseNamespace }}
          subset:
            values:
              version: {{ $version }}
        {{- end }}
    {{- end }}