steps:
  - helm3Deploy:
      releaseName: gloo
      namespace: gloo-system
      releaseUri: "https://storage.googleapis.com/solo-public-helm/charts/gloo-1.2.22.tgz"
      set:
        "license_key": "env:LICENSE_KEY"
      valuesFiles:
        - gloo-values.yaml
    title: Let's deploy gloo with an internal and external gateway proxy