apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petclinic-routes
  namespace: gloo-system
spec:
  routes:
    - matchers:
        - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petclinic-8080
            namespace: gloo-system