# Pre-requisites:
# - `valet ensure -f ../common/workflows/deploy-gloo-enterprise.yaml`
title: Delegating route ownership with Route Tables
description:
  - >
    In this workflow, we'll set up the petclinic application, which
    consists of a backend server and a database. Once this application is configured in Gloo, we'll look at how you
    can utilize **delegation** to enable teams to manage their own routes while an admin can manage the overall domain.
  - >
    This workflow assumes you already have a Kubernetes cluster, and you've installed Gloo Enterprise to the gloo-system namespace.
steps:
  - workflow:
      path: ../../../common/workflows/deploy-petclinic.yaml
  - workflow:
      path: 2-configure-routetable.yaml